const API = "http://127.0.0.1:8011";
const state = {
  sessions: [], folders: [], prompts: [], schedules: [], auditLogs: [], documents: [], analytics: null, status: null, activeSessionId: null, messages: [], stopStreaming: false,
  preferences: { theme: "dark", response_style: "balanced", persona: "professional", temperature: 0.3, use_rag: true, use_agents: false, voice_enabled: false, streaming_enabled: true, wide_mode: true, distraction_free: false, show_sources: true, privacy_mode: false, model: "smart" },
};
const app = document.getElementById("app");
function escapeHtml(value) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#39;"); }
async function api(path, options = {}) { const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options }); const contentType = response.headers.get("content-type") || ""; const payload = contentType.includes("application/json") ? await response.json() : await response.text(); if (!response.ok) { const detail = typeof payload === "string" ? payload : payload.detail || payload.error || "Request failed"; throw new Error(detail); } return payload; }
function activeSession() { return state.sessions.find((session) => session.id === state.activeSessionId); }
function formatTimestamp(value) { return new Date(value || Date.now()).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }); }
function option(value, label, selected) { return `<option value="${value}" ${String(value) === String(selected) ? "selected" : ""}>${label}</option>`; }
function renderNavItem(label, action) { return `<button class="nav-item" onclick="${action}">${label}</button>`; }
function renderSessionItem(session) { return `<button class="thread-item ${session.id === state.activeSessionId ? "active" : ""}" onclick="loadSession('${session.id}')"><div class="thread-title">${escapeHtml(session.title || "New chat")}</div><div class="thread-meta">${escapeHtml(session.summary || "No messages yet")}</div></button>`; }
function renderMessageBody(content) { const codeFence = /```(\w+)?\n([\s\S]*?)```/g; let lastIndex = 0; let output = ""; let match; while ((match = codeFence.exec(content)) !== null) { output += `<div>${escapeHtml(content.slice(lastIndex, match.index))}</div>`; const lang = match[1] || "markup"; output += `<div class="code-block"><pre><code class="language-${escapeHtml(lang)}">${escapeHtml(match[2])}</code></pre></div>`; lastIndex = codeFence.lastIndex; } output += `<div>${escapeHtml(content.slice(lastIndex))}</div>`; return output; }
function renderSourcePills(sources) { if (!state.preferences.show_sources || !sources.length) return ""; return `<div class="source-list">${sources.map((source) => `<div class="source-pill"><div class="source-title">${escapeHtml(source.source || source.title || "Source")}</div><div class="source-url">${escapeHtml(source.url || source.snippet || "")}</div></div>`).join("")}</div>`; }
function renderMessage(message, index) { const role = message.role || message.type || "assistant"; const label = role === "user" ? "You" : role === "system" ? "System" : role === "error" ? "Error" : "VIRA"; return `<article class="message ${escapeHtml(role)}"><div class="message-header"><div class="message-author">${label}</div><div class="message-time">${formatTimestamp(message.timestamp)}</div></div><div class="message-body">${renderMessageBody(message.content || "")}</div>${renderSourcePills(message.metadata?.sources || [])}<div class="message-actions"><button class="text-button" onclick="copyText(${index})">Copy</button><button class="text-button" onclick="regenerateFrom(${index})">Regenerate</button>${role === "user" ? `<button class="text-button" onclick="editPrompt(${index})">Edit</button>` : ""}</div></article>`; }
function renderHomeState() { return `<div class="home-state"><div class="home-brand">VIRA</div><h1>Ready when you are.</h1><p>Professional AI assistance for research, writing, coding, planning, and document-based answers.</p><div class="home-actions"><button class="home-chip" onclick="applyStarter('Explain this clearly and professionally with key points and a short summary.')">Explain clearly</button><button class="home-chip" onclick="applyStarter('Research this topic and give me the most useful information with sources.')">Research</button><button class="home-chip" onclick="applyStarter('Help me draft a professional answer for this task.')">Draft answer</button><button class="home-chip" onclick="applyStarter('Analyze this file and answer based on its contents.')">Analyze file</button></div></div>`; }
function renderCheckbox(label, key) { return `<span class="option-label">${label}</span><input type="checkbox" ${state.preferences[key] ? "checked" : ""} onchange="updatePref('${key}', this.checked)">`; }
function renderComposer() { return `<section class="composer-shell"><div class="composer-frame"><button class="composer-icon" onclick="uploadDocuments()" title="Upload files">+</button><textarea id="chatInput" placeholder="Ask anything" onkeydown="handleComposerKey(event)"></textarea><div class="composer-tools"><button class="composer-mini" onclick="toggleVoice()" title="Voice">?</button><button class="composer-send" onclick="sendMessage()" title="Send">?</button></div></div><div class="composer-options"><label>${renderCheckbox("Use Files", "use_rag")}</label><label>${renderCheckbox("Web Sources", "show_sources")}</label><label>${renderCheckbox("Agents", "use_agents")}</label><label>${renderCheckbox("Private", "privacy_mode")}</label><select onchange="updatePref('response_style', this.value)">${option("balanced", "Balanced", state.preferences.response_style)}${option("concise", "Concise", state.preferences.response_style)}${option("detailed", "Detailed", state.preferences.response_style)}${option("technical", "Technical", state.preferences.response_style)}</select><select onchange="updatePref('model', this.value)">${option("smart", "Smart", state.preferences.model)}${option("fast", "Fast", state.preferences.model)}</select></div><input id="fileInput" type="file" multiple hidden onchange="handleFiles(event)"></section>`; }
function render() { const session = activeSession(); const status = state.status?.status || "offline"; app.innerHTML = `<div class="shell"><aside class="sidebar"><div class="sidebar-top"><div class="logo">V</div>${renderNavItem("New chat", "createSession()")}${renderNavItem("Search chats", "focusSearch()")}${renderNavItem("Files", "uploadDocuments()")}${renderNavItem("Prompts", "showPromptShortcut()")}</div><div class="sidebar-section"><div class="section-title">Recent</div><div class="thread-list">${state.sessions.map(renderSessionItem).join("") || `<div class="empty-side">No chats yet</div>`}</div></div><div class="sidebar-footer">VIRA</div></aside><main class="main-panel"><header class="topbar"><div class="topbar-title">VIRA</div><div class="topbar-status"><span class="status-dot ${status === "operational" ? "online" : ""}"></span><span>${escapeHtml(status)}</span></div></header><section class="conversation ${state.messages.length ? "active" : "idle"}">${state.messages.length ? `<div class="messages">${state.messages.map(renderMessage).join("")}</div>` : renderHomeState()}</section><div class="composer-wrap">${renderComposer()}<div class="footer-note">${session ? `${escapeHtml(session.title)} · ${session.token_estimate || 0} tokens` : "Professional mode enabled"}</div></div></main></div>`; hydrateCodeBlocks(); }
function hydrateCodeBlocks() { if (window.Prism) window.Prism.highlightAll(); }
async function refreshAll() { const [sessions, folders, prompts, docs, analytics, status, schedules, audit] = await Promise.all([api("/sessions"), api("/folders"), api("/prompts"), api("/documents"), api("/analytics"), api("/status"), api("/schedules"), api("/audit-logs")]); state.sessions = sessions.sessions || []; state.folders = folders.folders || []; state.prompts = prompts.prompts || []; state.documents = docs.documents || []; state.analytics = analytics; state.status = status; state.schedules = schedules.schedules || []; state.auditLogs = audit.logs || []; if (!state.activeSessionId && state.sessions.length) state.activeSessionId = state.sessions[0].id; if (state.activeSessionId) await loadSession(state.activeSessionId, true); render(); }
async function createSession() { const payload = await api("/sessions", { method: "POST", body: JSON.stringify({ title: "New chat", folder_id: state.folders[0]?.id || "general" }) }); state.activeSessionId = payload.session.id; state.messages = []; await refreshAll(); }
async function loadSession(sessionId, silent = false) { const payload = await api(`/history/${encodeURIComponent(sessionId)}`); state.activeSessionId = sessionId; state.messages = payload.history || []; state.preferences = { ...state.preferences, ...(payload.preferences || {}) }; if (!silent) render(); }
async function updatePref(key, value) { state.preferences[key] = value; render(); if (!state.activeSessionId) return; await api(`/preferences/${encodeURIComponent(state.activeSessionId)}`, { method: "PATCH", body: JSON.stringify({ [key]: value }) }); }
async function sendMessage() { const input = document.getElementById("chatInput"); const message = input.value.trim(); if (!message) return; if (!state.activeSessionId) await createSession(); state.stopStreaming = false; state.messages.push({ type: "user", role: "user", content: message, timestamp: new Date().toISOString(), metadata: {} }); input.value = ""; render(); const payload = await api("/chat", { method: "POST", body: JSON.stringify({ session_id: state.activeSessionId, message, use_rag: state.preferences.use_rag, use_agents: state.preferences.use_agents, use_web: state.preferences.show_sources, speak: state.preferences.voice_enabled, streaming: state.preferences.streaming_enabled, temperature: Number(state.preferences.temperature), persona: state.preferences.persona, response_style: state.preferences.response_style, model: state.preferences.model, privacy_mode: state.preferences.privacy_mode }) }); const placeholder = { type: payload.error ? "error" : "assistant", role: "assistant", content: "", timestamp: new Date().toISOString(), metadata: { sources: payload.sources || [] } }; state.messages.push(placeholder); render(); await streamResponse(placeholder, payload.response || payload.error || "No response."); await refreshAll(); }
async function streamResponse(targetMessage, content) { const words = content.split(" "); let current = ""; for (const word of words) { if (state.stopStreaming) break; current += (current ? " " : "") + word; targetMessage.content = current; render(); await new Promise((resolve) => setTimeout(resolve, 18)); } targetMessage.content = state.stopStreaming ? `${current}\n\n[Stopped by user]` : content; render(); }
function handleComposerKey(event) { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); sendMessage(); } }
function toggleVoice() { updatePref("voice_enabled", !state.preferences.voice_enabled); }
function uploadDocuments() { document.getElementById("fileInput")?.click(); }
async function handleFiles(event) { const files = Array.from(event.target.files || []); for (const file of files) { const formData = new FormData(); formData.append("file", file); formData.append("session_id", state.activeSessionId || "default"); await fetch(`${API}/upload`, { method: "POST", body: formData }); } event.target.value = ""; await refreshAll(); }
function applyStarter(text) { const input = document.getElementById("chatInput"); if (!input) return; input.value = text; input.focus(); }
function copyText(index) { navigator.clipboard.writeText(state.messages[index].content || ""); }
async function regenerateFrom(index) { const base = state.messages[index]; if (!base) return; const input = document.getElementById("chatInput"); if (!input) return; input.value = base.content || ""; await sendMessage(); }
async function editPrompt(index) { const message = state.messages[index]; if (!(message.role === "user" || message.type === "user")) return; const next = prompt("Edit message", message.content); if (!next) return; await api("/messages/edit", { method: "PATCH", body: JSON.stringify({ session_id: state.activeSessionId, message_index: index, content: next }) }); await loadSession(state.activeSessionId); }
function focusSearch() { alert("Search chat history is coming next."); }
function showPromptShortcut() { if (!state.prompts.length) { alert("No prompts saved yet."); return; } applyStarter(state.prompts[0].content); }
window.createSession = createSession; window.loadSession = loadSession; window.sendMessage = sendMessage; window.handleComposerKey = handleComposerKey; window.uploadDocuments = uploadDocuments; window.handleFiles = handleFiles; window.applyStarter = applyStarter; window.copyText = copyText; window.regenerateFrom = regenerateFrom; window.editPrompt = editPrompt; window.toggleVoice = toggleVoice; window.focusSearch = focusSearch; window.showPromptShortcut = showPromptShortcut; window.updatePref = updatePref;
refreshAll().then(render).catch((error) => { app.innerHTML = `<div class="shell-error">Initialization failed: ${escapeHtml(error.message)}</div>`; });
